Repository kodoyoon/SunlightMarket, pull requests merged in 2023-12, with the labels that each got.

#6 feat: UserDetailsImpl.java , UserRoleEnum.java 구현
  src/main/java/com/raincloud/sunlightmarket/global/entity/UserRoleEnum.java
  src/main/java/com/raincloud/sunlightmarket/global/security/UserDetailsImpl.java
Labels: feat

#9 feat: security 기능 구현
  src/main/java/com/raincloud/sunlightmarket/global/config/WebSecurityConfig.java
  src/main/java/com/raincloud/sunlightmarket/global/jwt/JwtUtil.java
  src/main/java/com/raincloud/sunlightmarket/global/security/JwtAuthenticationFilter.java
  src/main/java/com/raincloud/sunlightmarket/global/security/JwtAuthentizationFilter.java
  src/main/java/com/raincloud/sunlightmarket/global/security/UserDetailsServiceImpl.java
Labels: feat

#10 feature/item read
  src/main/java/com/raincloud/sunlightmarket/global/dto/CommonResponseDto.java
  src/main/java/com/raincloud/sunlightmarket/global/entity/Timestamped.java
  src/main/java/com/raincloud/sunlightmarket/item/controller/ItemController.java
  src/main/java/com/raincloud/sunlightmarket/item/dto/ItemAllResponseDto.java
  src/main/java/com/raincloud/sunlightmarket/item/dto/ItemRequestDto.java
  src/main/java/com/raincloud/sunlightmarket/item/dto/ItemResponseDto.java
  src/main/java/com/raincloud/sunlightmarket/item/entity/Item.java
  src/main/java/com/raincloud/sunlightmarket/item/repository/ItemRepository.java
  src/main/java/com/raincloud/sunlightmarket/item/service/ItemService.java
Labels: feat

#15 Feat : User, Kakao 로그인 및 회원가입 구현
  src/main/java/com/raincloud/sunlightmarket/global/config/RestTemplateConfig.java
  src/main/java/com/raincloud/sunlightmarket/global/config/WebSecurityConfig.java
  src/main/java/com/raincloud/sunlightmarket/global/jwt/JwtUtil.java
  src/main/java/com/raincloud/sunlightmarket/global/security/JwtAuthenticationFilter.java
  src/main/java/com/raincloud/sunlightmarket/global/security/UserDetailsImpl.java
  src/main/java/com/raincloud/sunlightmarket/global/security/UserDetailsServiceImpl.java
  src/main/java/com/raincloud/sunlightmarket/user/controller/UserController.java
  src/main/java/com/raincloud/sunlightmarket/user/dto/KakaoUserInfoDto.java
  src/main/java/com/raincloud/sunlightmarket/user/dto/request/SingUpRequestDto.java
  src/main/java/com/raincloud/sunlightmarket/user/dto/response/SignUpResponseDto.java
  src/main/java/com/raincloud/sunlightmarket/user/entity/User.java
  src/main/java/com/raincloud/sunlightmarket/user/repository/UserRepository.java
  src/main/java/com/raincloud/sunlightmarket/user/service/KakaoService.java
  src/main/java/com/raincloud/sunlightmarket/user/service/UserService.java
Labels: feat

#23 Feat : User 프로필 수정 기능 구현
  src/main/java/com/raincloud/sunlightmarket/user/controller/UserController.java
  src/main/java/com/raincloud/sunlightmarket/user/dto/request/ProfileRequestDto.java
  src/main/java/com/raincloud/sunlightmarket/user/dto/response/ProfileResponseDto.java
  src/main/java/com/raincloud/sunlightmarket/user/entity/User.java
  src/main/java/com/raincloud/sunlightmarket/user/service/UserService.java
Labels: feat

#26 feat: Buyer&Seller Entity 기능 구현
  src/main/java/com/raincloud/sunlightmarket/user/entity/Buyer.java
  src/main/java/com/raincloud/sunlightmarket/user/entity/Seller.java
  src/main/java/com/raincloud/sunlightmarket/user/entity/User.java
  src/main/java/com/raincloud/sunlightmarket/user/repository/BuyerRepository.java
  src/main/java/com/raincloud/sunlightmarket/user/repository/SellerRepository.java
  src/main/java/com/raincloud/sunlightmarket/user/service/UserService.java
Labels: feat

#24 Feat : User 내 프로필 조회 기능 구현
  src/main/java/com/raincloud/sunlightmarket/item/entity/Item.java
  src/main/java/com/raincloud/sunlightmarket/user/controller/UserController.java
  src/main/java/com/raincloud/sunlightmarket/user/dto/request/MyProfileRequestDto.java
  src/main/java/com/raincloud/sunlightmarket/user/dto/response/MyProfileResponseDto.java
  src/main/java/com/raincloud/sunlightmarket/user/dto/response/UserProfileResponseDto.java
  src/main/java/com/raincloud/sunlightmarket/user/entity/Seller.java
  src/main/java/com/raincloud/sunlightmarket/user/service/UserService.java
Labels: feat

#35 feat: Review To Seller 리뷰 수정,삭제 기능 구현
  src/main/java/com/raincloud/sunlightmarket/review/toseller/controller/ReviewToSellerController.java
  src/main/java/com/raincloud/sunlightmarket/review/toseller/dto/response/UpdateReviewToSellerResponseDto.java
  src/main/java/com/raincloud/sunlightmarket/review/toseller/entity/ReviewToSeller.java
  src/main/java/com/raincloud/sunlightmarket/review/toseller/service/ReviewToSellerService.java
Labels: feat

#36 Feat: Order Create 기능 구현
  src/main/java/com/raincloud/sunlightmarket/item/controller/ItemController.java
  src/main/java/com/raincloud/sunlightmarket/item/entity/Item.java
  src/main/java/com/raincloud/sunlightmarket/order/controller/OrderController.java
  src/main/java/com/raincloud/sunlightmarket/order/dto/OrderRequestDto.java
  src/main/java/com/raincloud/sunlightmarket/order/dto/OrderResponseDto.java
  src/main/java/com/raincloud/sunlightmarket/order/entity/Order.java
  src/main/java/com/raincloud/sunlightmarket/order/repository/OrderRepository.java
  src/main/java/com/raincloud/sunlightmarket/order/service/OrderService.java
  src/main/java/com/raincloud/sunlightmarket/user/entity/Buyer.java
  src/main/java/com/raincloud/sunlightmarket/user/repository/BuyerRepository.java
Labels: feat

#37 Feat: 아이템을 올린 유저는 구매 요청을 할 수 없게 함
  src/main/java/com/raincloud/sunlightmarket/order/controller/OrderController.java
  src/main/java/com/raincloud/sunlightmarket/order/dto/OrderRequestDto.java
  src/main/java/com/raincloud/sunlightmarket/order/service/OrderService.java
Labels: feat

#38 Refactor: Join된 Column으로 Entity조회할 때 따로 Repository에 함수를 안 거치도록 수정
  src/main/java/com/raincloud/sunlightmarket/item/service/ItemService.java
Labels: feat

#40 feat: Review To Seller 좋아요 기능 구현
  src/main/java/com/raincloud/sunlightmarket/review/toseller/controller/ReviewToSellerController.java
  src/main/java/com/raincloud/sunlightmarket/review/toseller/entity/ReviewToSeller.java
  src/main/java/com/raincloud/sunlightmarket/review/toseller/service/ReviewToSellerService.java
  src/main/java/com/raincloud/sunlightmarket/user/entity/Seller.java
Labels: feat

#45 Feat : User 비밀번호 수정 기능 구현
  src/main/java/com/raincloud/sunlightmarket/user/controller/UserController.java
  src/main/java/com/raincloud/sunlightmarket/user/dto/request/PasswordRequestDto.java
  src/main/java/com/raincloud/sunlightmarket/user/entity/User.java
  src/main/java/com/raincloud/sunlightmarket/user/service/UserService.java
Labels: feat

#48 Feat : Order Confirm 기능 구현
  src/main/java/com/raincloud/sunlightmarket/item/entity/Item.java
  src/main/java/com/raincloud/sunlightmarket/order/controller/OrderController.java
  src/main/java/com/raincloud/sunlightmarket/order/entity/Order.java
  src/main/java/com/raincloud/sunlightmarket/order/service/OrderService.java
Labels: feat

#49 Feat : 내 Order들 조회 기능 구현
  src/main/java/com/raincloud/sunlightmarket/order/controller/OrderController.java
  src/main/java/com/raincloud/sunlightmarket/order/repository/OrderRepository.java
  src/main/java/com/raincloud/sunlightmarket/order/service/OrderService.java
Labels: feat

#52 Refactor: OrderStatus Enum 만듦
  src/main/java/com/raincloud/sunlightmarket/order/dto/OrderResponseDto.java
  src/main/java/com/raincloud/sunlightmarket/order/dto/PublicOrderResponseDto.java
  src/main/java/com/raincloud/sunlightmarket/order/entity/Order.java
  src/main/java/com/raincloud/sunlightmarket/order/entity/OrderStatus.java
  src/main/java/com/raincloud/sunlightmarket/order/repository/OrderRepository.java
  src/main/java/com/raincloud/sunlightmarket/order/service/OrderService.java
Labels: feat

#55 Feature/logout
  src/main/java/com/raincloud/sunlightmarket/global/config/WebSecurityConfig.java
  src/main/java/com/raincloud/sunlightmarket/global/jwt/JwtEntity.java
  src/main/java/com/raincloud/sunlightmarket/global/jwt/JwtUtil.java
  src/main/java/com/raincloud/sunlightmarket/global/jwt/TokenRepository.java
  src/main/java/com/raincloud/sunlightmarket/global/security/JwtAuthenticationFilter.java
  src/main/java/com/raincloud/sunlightmarket/global/security/JwtAuthorizationFilter.java
  src/main/java/com/raincloud/sunlightmarket/global/security/UserDetailsServiceImpl.java
  src/main/java/com/raincloud/sunlightmarket/review/tobuyer/controller/ReviewToBuyerController.java
  src/main/java/com/raincloud/sunlightmarket/review/tobuyer/dto/request/ReviewToBuyerRequestDto.java
  src/main/java/com/raincloud/sunlightmarket/review/tobuyer/dto/response/CreateReviewToBuyerResponseDto.java
  src/main/java/com/raincloud/sunlightmarket/review/tobuyer/dto/response/UpdateReviewToBuyerResponseDto.java
  src/main/java/com/raincloud/sunlightmarket/review/tobuyer/entity/ReviewToBuyer.java
  src/main/java/com/raincloud/sunlightmarket/review/tobuyer/repository/ReviewToBuyerRepository.java
  src/main/java/com/raincloud/sunlightmarket/review/tobuyer/service/ReviewToBuyerService.java
  src/main/java/com/raincloud/sunlightmarket/user/controller/UserController.java
  src/main/java/com/raincloud/sunlightmarket/user/entity/Buyer.java
  src/main/java/com/raincloud/sunlightmarket/user/entity/User.java
  src/main/java/com/raincloud/sunlightmarket/user/service/UserService.java
Labels: refactor, feat

#58 Hotfix : 인증인가 부분 수정, 유저컨트롤러 ApiResponse 변경
  src/main/java/com/raincloud/sunlightmarket/global/jwt/JwtUtil.java
  src/main/java/com/raincloud/sunlightmarket/global/security/JwtAuthorizationFilter.java
  src/main/java/com/raincloud/sunlightmarket/user/controller/UserController.java
Labels: bug
